### ISSUE TITLE
HTTP 500 when not supplying api key

### ISSUE THREAD

**Issue by Drummersbrother** [RocketLeagueStats/rls-api#10]
The api returns an empty http 500 response when an authorisation header or authorisation query param is not supplied to an endpoint.
I have tested the `/data/seasons` and `/search/players` endpoints, and they both exhibit this behaviour.
I assume the intended behaviour is for them to return HTTP 400 or 401 in the future.

**Comment by AeonLucid** [comment]
Can not reproduce anymore, I think it's fixed.
