### ISSUE TITLE
data.rankedSeasons returns an Object which I can't do anything with it.

### ISSUE THREAD

**Issue by estevE11** [RocketLeagueStats/rls-api#12]
When I console.log data.rankedSeasons, it returns the following:
{ '5': 
   { '10': { rankPoints: 325, matchesPlayed: 463, tier: 2, division: 3 },
     '11': { rankPoints: 450, matchesPlayed: 662, tier: 4, division: 3 },
     '12': { rankPoints: 591, matchesPlayed: 6, tier: 0, division: 0 },
     '13': { rankPoints: 538, matchesPlayed: 71, tier: 6, division: 0 } } }

It seems like a JSON Object, but I try to parse it and it gives me an error.

In fact this: JSON.parse(data.rankedSeasons); Tries to parse "[Object object]".

Thanks 😉

**Comment by AeonLucid** [comment]
What language? Any libraries you use?

**Comment by estevE11** [comment]
NodeJS with discord.js

**Comment by estevE11** [comment]
hi? 😅

**Comment by Drummersbrother** [comment]
I tried to parse that string (just copypasted it, @Coconaut11 please use code blocks :smile: ) in python, and it didn't work. I believe the error is that `rankPoints`, `matchesPlayed`, and `division` aren't enclosed in quotes, as the JSON specs say they should be.

**Comment by estevE11** [comment]
Is there any solution?

**Comment by Drummersbrother** [comment]
My library uses that endpoint, and my tests run fine, so I believe the error is at your end. Maybe your http library isn't working properly when it comes to escaping quotes or something :man_shrugging:

**Comment by AeonLucid** [comment]
Please share code that reproduces your error so we can look at it.

**Comment by estevE11** [comment]
Here is it:
`         
            global.rls_client.getPlayer(name, global.rls.platforms.STEAM, function(status, data){
            
                if(status === 200) {
                
                let embed = new Discord.RichEmbed();
                console.log(data.rankedSeasons);
                let rs = JSON.parse(data.rankedSeasons);
                console.log(rs);

                msg.channel.sendEmbed(embed);
            } else {
                msg.channel.send("Player not found");
            }
        });`

**Comment by Drummersbrother** [comment]
If you're writing javascript, maybe it already converted `data.rankedSeasons` to a javascript object, and you're trying to parse it again, therefore that error message?

**Comment by AeonLucid** [comment]
I believe that's exactly what is happening, you don't have to parse it again.

**Comment by estevE11** [comment]
No, I try, per example `data.rankedSeassons.10`, and it gives me a syntaxis error

**Comment by Drummersbrother** [comment]
Because the keys are strings? I don't think JSON supports integer keys
I'm not a JS programmer, but I believe you're looking for `data.rankedSeasons["10"]`

**Comment by estevE11** [comment]
Yes, but then what should I do? JSON doesn't suppot integer keys, then how can I get the value?
Because even `data.rankedSeassons.toString()` retunrs "[Object object]".

**Comment by Drummersbrother** [comment]
Maybe `data.rankedSeasons["NUMBER HERE, BUT IN QUOTES"]`
I'm not a JS programmer though.

**Comment by estevE11** [comment]
Ok, I'll try, thx.

**Comment by estevE11** [comment]
Nah, it returns undefined... 😅

**Comment by Drummersbrother** [comment]
Which key and which object did you use? In your original example `data.rankedSeasons["5"]` is the only one.

**Comment by estevE11** [comment]
jajaj I actually tried `console.log(data.rankedSeasons["10"].tier);`

**Comment by Drummersbrother** [comment]
Yeah that doesn't exist in the original data.

**Comment by estevE11** [comment]
Nah but still `undefined` with num 10

**Comment by Drummersbrother** [comment]
Please try `console.log(data.rankedSeasons["5"]["10"].tier);`

**Comment by estevE11** [comment]
Yeah, finally, thank you very much.. I'm stupid today 😅, of course it's not just `["10"]`.
Thanks!

**Comment by AeonLucid** [comment]
I think `console.log(data.rankedSeasons.5.10.tier)` works too. Can't test right now because of mobile.
