### ISSUE TITLE
Single player endpoint not working with my ID

### ISSUE THREAD

**Issue by Girbons** [RocketLeagueStats/rls-api#14]
The single player endpoint seems broken using my ID, the following call returns a 500:

`https://api.rocketleaguestats.com/v1/player?unique_id=76561198079681869&platform_id=1`

It seems not working since the 9th of September

**Comment by AeonLucid** [comment]
Please include the error message hash.

**Comment by Girbons** [comment]
Yes sorry,

That's the response:
```json
{
  "code": 500,
  "message": "We had a problem with our server. (d291cf780a51450881ba0e2b284c945c)"
}
```

**Comment by AeonLucid** [comment]
Same issue: https://twitter.com/Barbosicks/status/903734068059275264

I have **possibly** implemented a fix. This is a really weird error for which I just have to try some things and see what works and what doesn't.

**Comment by estevE11** [comment]
Stopped working again. Error code: 500.

**Comment by Girbons** [comment]
It works now

**Comment by AeonLucid** [comment]
It stopped working again, rolling out another update which **might** fix it.

**Comment by estevE11** [comment]
Will it fix it forever?

**Comment by AeonLucid** [comment]
@Coconaut11 Hopefully :)

**Comment by estevE11** [comment]
Well, it stopped working again...

**Comment by AeonLucid** [comment]
@Coconaut11 Is it still not working?

**Comment by Girbons** [comment]
Nope, it stopped working 2 days ago

**Comment by estevE11** [comment]
The error i got
{
	"code": 500,
	"message": "We had a problem with our server. (Exception hash: a588050e54a94698ac3a57856c278fbc)"
}

That was my GET: 
https://api.rocketleaguestats.com/v1/player?unique_id=76561198088744213&platform_id=1&apikey=<...>

**Comment by estevE11** [comment]
It works like in very short periods of time.

**Comment by AeonLucid** [comment]
Closing to replace with a more explaining issue. (https://github.com/RocketLeagueStats/rls-api/issues/15)
