### ISSUE TITLE
Prioritize people with matches played in Search API.

### ISSUE THREAD

**Issue by ivanfeli** [RocketLeagueStats/rls-api#16]
Prioritize players with games played above those who have no games played (current season).

For example: searching "pol" right now, the first ~20 results are all players who have 0 matches played this season.

**Comment by oparkerj** [comment]
I think a lot of people would find this useful. It may be better to implement it as "display filters" so that it's easy to add any more like this in the future.

**Comment by ivanfeli** [comment]
Any updates/progress on this?

**Comment by AeonLucid** [comment]
Done!
Players with most matches played in season 6 are now on top.
