### ISSUE TITLE
Seasons API response showing incorrect season 3 start date

### ISSUE THREAD

**Issue by ghost** [RocketLeagueStats/rls-api#24]
Making this request `https://api.rocketleaguestats.com/v1/data/seasons` returns this:

`
{
        "seasonId": 2,
        "startedOn": 1455062400,
        "endedOn": 1466467200
    },
    {
        "seasonId": 3,
        "startedOn": 1434844800,
        "endedOn": 1458604800
    },
`

Season 2 ended on is `1466467200` which is June 21, **2016**, but season 3 starts on `1434844800` which is  June 21, **2015**.

**Comment by nikkelma** [comment]
I thought this looked iffy when looking through it in my own debugging of data, thanks for not being lazy like me! Seems like three values need to be updated: Season 3 start, Season 3 end, and Season 4 start.

Current data in the API:
Season 1 started September 10, 2015, ended February 10, 2016
Season 2 started February 10 2016, ended June 21, 2016
Season 3 started June 21 **2015**, ended March 22, **2016**
Season 4 started March 22, **2016**, ended July 5, 2017
Season 5 started July 5, 2017, ended September 28, 2017
Season 6 started September 28, 2017, ended February 8, 2018
Season 7 started February 8, 2018
