### ISSUE TITLE
Player lookup fails for some ps4 players

### ISSUE THREAD

**Issue by jake73345634634** [RocketLeagueStats/rls-api#3]
![image](https://user-images.githubusercontent.com/22551835/28289912-5bd56484-6b3c-11e7-9f67-cf0549613b9e.png)

Trying to curl with the /v1/player? endpoint returning: **"Player was inserted but our sanity check failed, please notify us."**

`curl "https://api.rocketleaguestats.com/v1/player?unique_id=shadowinsaanity&platform_id=2" \ -H "Authorization: xd"`

**Comment by andiCR** [comment]
Hey Aeon, here's a list of PSN players i'm having trouble with:
- Kesare17
- AndresCS117
- edamazzio
- jujoar10
- Diego1287
- kevinJA_CR
- armando-_-2214cr
- ErickJ_CR
- ATOSI12

Thanks and gl

**Comment by AeonLucid** [comment]
Finally fixed it 😄 

Can you both confirm that so I can close the issue? @Jake-Ruston @andiCR

**Comment by andiCR** [comment]
Thanks Aeon, everything seems to be working at the moment.
