### ISSUE TITLE
HTTP 500 when POSTing valid but not the right format json to /v1/player/batch endpoint.

### ISSUE THREAD

**Issue by Drummersbrother** [RocketLeagueStats/rls-api#5]
The `/v1/player/batch` endpoint should return an HTTP 400 (in accordance with [this response code table](http://documentation.rocketleaguestats.com/#response-codes)) when the data it gets is not in the proper format.

What happens now is that it returns an HTTP 500 error, with an empty body `Content-Length: 0`.

Example:
```
POST Data, note the invalid key "platforId", it's missing an m:

[{'uniqueId': '76561198075106985', 'platforId': '1'}, 
{'uniqueId': '76561198080931713', 'platforId': '1'}, 
{'uniqueId': '76561198087110443', 'platforId': '1'}]
```
That data (coupled with an otherwise valid request) returns an HTTP 500 response code, instead of the HTTP 400 it should return.
If you replace `'platforId'` with `'platformId'` in that json data, then the response is as expected an HTTP 200.

**Comment by AeonLucid** [comment]
Fixed.
