### ISSUE TITLE
Merge the PR Artful made

### ISSUE THREAD

**Issue by ghost** [RocketLeagueStats/rls-api#8]
Do i have to explain what i mean?

**Comment by AeonLucid** [comment]
As soon as throttling is added to make it a proper rewrite. Also, please create the issue on the relevant repo. You could've commented on the pr itself too.

**Comment by ghost** [comment]
He asked you to add Throttling

**Comment by AeonLucid** [comment]
I'll do it when I have time.

**Comment by ghost** [comment]
Kek

**Comment by ghost** [comment]
i'll be waiting
